function [] = spikeGUI(T,D,Z)
% global FIGURE

chan=1;
X=D(chan,:);
Z0=Z(chan,:);
tmin=T(1);
tmax=T(end);
ymin=1.05*min(min(X));
ymax=1.05*max(max(X));

% initialize figure
close all;
FIGURE = figure('units','normalized', ...
  'position', [0.01 0.01 0.97 0.95], ...
  'menubar', 'none', ...
  'name', 'Spike Finder GUI', ...
  'numbertitle', 'off', ...
  'resize', 'off');

Fs=round(1/(T(2)-T(1))); dt_ms = round(Fs/1e3);
dT_list = cell(1,250);
for t = 1:250, dT_list{t}=[num2str(t*2) ' ms (' num2str(round(t*2*dt_ms)) ' bins)']; end

MAINPLOT = axes('position',[0.04 0.1 0.95 0.83], 'unit','normalized');
MENUS(1) = uicontrol('style','pop',...
                 'unit','normalized',...
                 'position',[0.01 0.79 0.15 0.2],...
                 'backgroundc',get(FIGURE,'color'),...
                 'fontsize',12,'fontweight','bold',...
                 'string',dT_list,'value',1,...
                 'callback',{@dTLupdate});
MENUS(2) = uicontrol('style','pop',...
                 'unit','normalized',...
                 'position',[0.16 0.79 0.15 0.2],...
                 'backgroundc',get(FIGURE,'color'),...
                 'fontsize',12,'fontweight','bold',...
                 'string',dT_list,'value',1,...
                 'callback',{@dTRupdate});               
MENUS(3) = uicontrol('style','edit',...
                 'unit','normalized',...
                 'position',[0.32 0.94 0.05 0.05],...
                 'callback',{@thresh1update});
MENUS(4) = uicontrol('style','edit',...
                 'unit','normalized',...
                 'position',[0.38 0.94 0.05 0.05],...
                 'callback',{@thresh2update});
MENUS(5) = uicontrol('style','edit',...
                 'unit','normalized',...
                 'position',[0.44 0.94 0.05 0.05],...
                 'val',tmin,...
                 'callback',{@tminupdate});
MENUS(6) = uicontrol('style','edit',...
                 'unit','normalized',...
                 'position',[0.5 0.94 0.05 0.05],...
                 'val',tmax,...
                 'callback',{@tmaxupdate});
MENUS(7) = uicontrol('style','pop',...
                 'unit','normalized',...
                 'position',[0.56 0.94 0.05 0.05],...
                 'backgroundc',get(FIGURE,'color'),...
                 'fontsize',12,'fontweight','bold',...
                 'string',1:96,'value',1,...
                 'callback',{@channelupdate});
MENUS(8) = uicontrol('style','pop',...
                 'unit','normalized',...
                 'position',[0.62 0.79 0.15 0.2],...
                 'backgroundc',get(FIGURE,'color'),...
                 'fontsize',12,'fontweight','bold',...
                 'string',dT_list,'value',1,...
                 'callback',{@dTSupdate});
dTL = 2*dt_ms; dTR = 2*dt_ms; dTS = 2*dt_ms;
thresh1 = 1; thresh2 = 1;
           
redraw();

  %--- callback functions:
  function dTLupdate(src,evnt)
  dTL=get(src,'Value')*dt_ms; %dTL
  redraw();
  end

  function dTRupdate(src,evnt)
  dTR=get(src,'Value')*dt_ms; %dTR
  redraw();
  end

  function dTSupdate(src,evnt)
  dTS=get(src,'Value')*dt_ms; %dTS
  redraw();
  end

  function thresh1update(src,evnt)
  thresh1=str2num(get(src,'String')); %thresh1
  redraw();
  end

  function thresh2update(src,evnt)
  thresh2=str2num(get(src,'String')); %thresh2
  redraw();
  end

  function tminupdate(src,evnt)
  tmin=str2num(get(src,'String')); %tmin
  xlim([tmin,tmax]);
  end

  function tmaxupdate(src,evnt)
  tmax=str2num(get(src,'String')); %tmax
  xlim([tmin,tmax]);
  end

  function channelupdate(src,evnt)
  chan=get(src,'Value'); %chan
  X=D(chan,:);
  Z0=Z(chan,:);
  ymin=1.05*min(min(X));
  ymax=1.05*max(max(X));
  redraw();
  end

  % plotting:
  function redraw()
    % go to subplot, i.e. set axes      
%     spk = spikefind4(-zscore(X),thresh1,dTL,thresh2,dTR);
    axes(MAINPLOT)
%   spk = spikefind2(Z0,thresh1,dTL); 
%   spk = spikefind3(Z0,thresh1,dTL,thresh2);
%     spk = spikefind4(Z0,thresh1,dTL,thresh2,dTR);
    spk = spikefind5(Z0,thresh1,dTL,thresh2,dTR,dTS);
    
    hold off; 
    plot(T,X); hold on;
    plot(T(spk),X(spk),'rx','markersize',8,'linewidth',2);
    xlim([tmin,tmax]);
    ylim([ymin,ymax]);
    pause(0.02);
  end

end